// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	DisplayName   string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Role          int32                  `protobuf:"varint,9,opt,name=role,proto3" json:"role,omitempty"`
	Group         string                 `protobuf:"bytes,10,opt,name=group,proto3" json:"group,omitempty"`
	Source        string                 `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	Remark        string                 `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *User) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *User) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *User) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_proto_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *Tenant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ApiKey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Key                string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status             int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ModelLimitsEnabled bool                   `protobuf:"varint,6,opt,name=model_limits_enabled,json=modelLimitsEnabled,proto3" json:"model_limits_enabled,omitempty"`
	ModelLimits        string                 `protobuf:"bytes,7,opt,name=model_limits,json=modelLimits,proto3" json:"model_limits,omitempty"`
	ExpireTime         int64                  `protobuf:"varint,8,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	AllowIps           string                 `protobuf:"bytes,9,opt,name=allow_ips,json=allowIps,proto3" json:"allow_ips,omitempty"`
	Group              string                 `protobuf:"bytes,10,opt,name=group,proto3" json:"group,omitempty"`
	LastUsedAt         int64                  `protobuf:"varint,11,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_proto_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *ApiKey) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApiKey) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApiKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKey) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ApiKey) GetModelLimitsEnabled() bool {
	if x != nil {
		return x.ModelLimitsEnabled
	}
	return false
}

func (x *ApiKey) GetModelLimits() string {
	if x != nil {
		return x.ModelLimits
	}
	return ""
}

func (x *ApiKey) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *ApiKey) GetAllowIps() string {
	if x != nil {
		return x.AllowIps
	}
	return ""
}

func (x *ApiKey) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ApiKey) GetLastUsedAt() int64 {
	if x != nil {
		return x.LastUsedAt
	}
	return 0
}

func (x *ApiKey) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *Role) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_proto_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *Permission) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	OauthId       string                 `protobuf:"bytes,6,opt,name=oauth_id,json=oauthId,proto3" json:"oauth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_proto_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RegisterReq) GetOauthId() string {
	if x != nil {
		return x.OauthId
	}
	return ""
}

type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_proto_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_proto_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_proto_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ValidateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenReq) Reset() {
	*x = ValidateTokenReq{}
	mi := &file_proto_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenReq) ProtoMessage() {}

func (x *ValidateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenRes struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserStatus         int32                  `protobuf:"varint,2,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	Group              string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	HasToken           bool                   `protobuf:"varint,4,opt,name=has_token,json=hasToken,proto3" json:"has_token,omitempty"`
	ApiKeyId           int64                  `protobuf:"varint,5,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	ModelLimitsEnabled bool                   `protobuf:"varint,6,opt,name=model_limits_enabled,json=modelLimitsEnabled,proto3" json:"model_limits_enabled,omitempty"`
	ModelLimits        []string               `protobuf:"bytes,7,rep,name=model_limits,json=modelLimits,proto3" json:"model_limits,omitempty"`
	KeyGroup           string                 `protobuf:"bytes,8,opt,name=key_group,json=keyGroup,proto3" json:"key_group,omitempty"`
	KeyUnlimitedQuota  bool                   `protobuf:"varint,9,opt,name=key_unlimited_quota,json=keyUnlimitedQuota,proto3" json:"key_unlimited_quota,omitempty"`
	KeyRemainQuota     int64                  `protobuf:"varint,10,opt,name=key_remain_quota,json=keyRemainQuota,proto3" json:"key_remain_quota,omitempty"`
	UserRole           int32                  `protobuf:"varint,11,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	TenantId           int64                  `protobuf:"varint,12,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidateTokenRes) Reset() {
	*x = ValidateTokenRes{}
	mi := &file_proto_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRes) ProtoMessage() {}

func (x *ValidateTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRes.ProtoReflect.Descriptor instead.
func (*ValidateTokenRes) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateTokenRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenRes) GetUserStatus() int32 {
	if x != nil {
		return x.UserStatus
	}
	return 0
}

func (x *ValidateTokenRes) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ValidateTokenRes) GetHasToken() bool {
	if x != nil {
		return x.HasToken
	}
	return false
}

func (x *ValidateTokenRes) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *ValidateTokenRes) GetModelLimitsEnabled() bool {
	if x != nil {
		return x.ModelLimitsEnabled
	}
	return false
}

func (x *ValidateTokenRes) GetModelLimits() []string {
	if x != nil {
		return x.ModelLimits
	}
	return nil
}

func (x *ValidateTokenRes) GetKeyGroup() string {
	if x != nil {
		return x.KeyGroup
	}
	return ""
}

func (x *ValidateTokenRes) GetKeyUnlimitedQuota() bool {
	if x != nil {
		return x.KeyUnlimitedQuota
	}
	return false
}

func (x *ValidateTokenRes) GetKeyRemainQuota() int64 {
	if x != nil {
		return x.KeyRemainQuota
	}
	return 0
}

func (x *ValidateTokenRes) GetUserRole() int32 {
	if x != nil {
		return x.UserRole
	}
	return 0
}

func (x *ValidateTokenRes) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type CreateApiKeyReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModelLimits        string                 `protobuf:"bytes,3,opt,name=model_limits,json=modelLimits,proto3" json:"model_limits,omitempty"`
	ModelLimitsEnabled bool                   `protobuf:"varint,4,opt,name=model_limits_enabled,json=modelLimitsEnabled,proto3" json:"model_limits_enabled,omitempty"`
	ExpireTime         int64                  `protobuf:"varint,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	AllowIps           string                 `protobuf:"bytes,6,opt,name=allow_ips,json=allowIps,proto3" json:"allow_ips,omitempty"`
	Group              string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateApiKeyReq) Reset() {
	*x = CreateApiKeyReq{}
	mi := &file_proto_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyReq) ProtoMessage() {}

func (x *CreateApiKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyReq.ProtoReflect.Descriptor instead.
func (*CreateApiKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *CreateApiKeyReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateApiKeyReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApiKeyReq) GetModelLimits() string {
	if x != nil {
		return x.ModelLimits
	}
	return ""
}

func (x *CreateApiKeyReq) GetModelLimitsEnabled() bool {
	if x != nil {
		return x.ModelLimitsEnabled
	}
	return false
}

func (x *CreateApiKeyReq) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *CreateApiKeyReq) GetAllowIps() string {
	if x != nil {
		return x.AllowIps
	}
	return ""
}

func (x *CreateApiKeyReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type CreateApiKeyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *ApiKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RawKey        string                 `protobuf:"bytes,2,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyRes) Reset() {
	*x = CreateApiKeyRes{}
	mi := &file_proto_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRes) ProtoMessage() {}

func (x *CreateApiKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRes.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRes) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *CreateApiKeyRes) GetApiKey() *ApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *CreateApiKeyRes) GetRawKey() string {
	if x != nil {
		return x.RawKey
	}
	return ""
}

type ListApiKeysReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysReq) Reset() {
	*x = ListApiKeysReq{}
	mi := &file_proto_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysReq) ProtoMessage() {}

func (x *ListApiKeysReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysReq.ProtoReflect.Descriptor instead.
func (*ListApiKeysReq) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *ListApiKeysReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListApiKeysReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListApiKeysReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListApiKeysRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*ApiKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysRes) Reset() {
	*x = ListApiKeysRes{}
	mi := &file_proto_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysRes) ProtoMessage() {}

func (x *ListApiKeysRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysRes.ProtoReflect.Descriptor instead.
func (*ListApiKeysRes) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *ListApiKeysRes) GetApiKeys() []*ApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *ListApiKeysRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteApiKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyReq) Reset() {
	*x = DeleteApiKeyReq{}
	mi := &file_proto_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyReq) ProtoMessage() {}

func (x *DeleteApiKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyReq.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteApiKeyReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteApiKeyReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteApiKeyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyRes) Reset() {
	*x = DeleteApiKeyRes{}
	mi := &file_proto_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyRes) ProtoMessage() {}

func (x *DeleteApiKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyRes.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyRes) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{16}
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_proto_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRes) Reset() {
	*x = GetUserRes{}
	mi := &file_proto_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRes) ProtoMessage() {}

func (x *GetUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRes.ProtoReflect.Descriptor instead.
func (*GetUserRes) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_proto_user_v1_user_proto protoreflect.FileDescriptor

const file_proto_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x18proto/user/v1/user.proto\x12\auser.v1\"\xe6\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x12\n" +
	"\x04role\x18\t \x01(\x05R\x04role\x12\x14\n" +
	"\x05group\x18\n" +
	" \x01(\tR\x05group\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\x12\x16\n" +
	"\x06remark\x18\f \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"D\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xd9\x02\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x120\n" +
	"\x14model_limits_enabled\x18\x06 \x01(\bR\x12modelLimitsEnabled\x12!\n" +
	"\fmodel_limits\x18\a \x01(\tR\vmodelLimits\x12\x1f\n" +
	"\vexpire_time\x18\b \x01(\x03R\n" +
	"expireTime\x12\x1b\n" +
	"\tallow_ips\x18\t \x01(\tR\ballowIps\x12\x14\n" +
	"\x05group\x18\n" +
	" \x01(\tR\x05group\x12 \n" +
	"\flast_used_at\x18\v \x01(\x03R\n" +
	"lastUsedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"L\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"f\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xa4\x01\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x19\n" +
	"\boauth_id\x18\x06 \x01(\tR\aoauthId\"x\n" +
	"\vRegisterRes\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"u\n" +
	"\bLoginRes\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"(\n" +
	"\x10ValidateTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xa3\x03\n" +
	"\x10ValidateTokenRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vuser_status\x18\x02 \x01(\x05R\n" +
	"userStatus\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x1b\n" +
	"\thas_token\x18\x04 \x01(\bR\bhasToken\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x05 \x01(\x03R\bapiKeyId\x120\n" +
	"\x14model_limits_enabled\x18\x06 \x01(\bR\x12modelLimitsEnabled\x12!\n" +
	"\fmodel_limits\x18\a \x03(\tR\vmodelLimits\x12\x1b\n" +
	"\tkey_group\x18\b \x01(\tR\bkeyGroup\x12.\n" +
	"\x13key_unlimited_quota\x18\t \x01(\bR\x11keyUnlimitedQuota\x12(\n" +
	"\x10key_remain_quota\x18\n" +
	" \x01(\x03R\x0ekeyRemainQuota\x12\x1b\n" +
	"\tuser_role\x18\v \x01(\x05R\buserRole\x12\x1b\n" +
	"\ttenant_id\x18\f \x01(\x03R\btenantId\"\xe7\x01\n" +
	"\x0fCreateApiKeyReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fmodel_limits\x18\x03 \x01(\tR\vmodelLimits\x120\n" +
	"\x14model_limits_enabled\x18\x04 \x01(\bR\x12modelLimitsEnabled\x12\x1f\n" +
	"\vexpire_time\x18\x05 \x01(\x03R\n" +
	"expireTime\x12\x1b\n" +
	"\tallow_ips\x18\x06 \x01(\tR\ballowIps\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\"T\n" +
	"\x0fCreateApiKeyRes\x12(\n" +
	"\aapi_key\x18\x01 \x01(\v2\x0f.user.v1.ApiKeyR\x06apiKey\x12\x17\n" +
	"\araw_key\x18\x02 \x01(\tR\x06rawKey\"Z\n" +
	"\x0eListApiKeysReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"R\n" +
	"\x0eListApiKeysRes\x12*\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x0f.user.v1.ApiKeyR\aapiKeys\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\":\n" +
	"\x0fDeleteApiKeyReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x11\n" +
	"\x0fDeleteApiKeyRes\"%\n" +
	"\n" +
	"GetUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"/\n" +
	"\n" +
	"GetUserRes\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user2\xb9\x03\n" +
	"\vUserService\x126\n" +
	"\bRegister\x12\x14.user.v1.RegisterReq\x1a\x14.user.v1.RegisterRes\x12-\n" +
	"\x05Login\x12\x11.user.v1.LoginReq\x1a\x11.user.v1.LoginRes\x12E\n" +
	"\rValidateToken\x12\x19.user.v1.ValidateTokenReq\x1a\x19.user.v1.ValidateTokenRes\x12B\n" +
	"\fCreateApiKey\x12\x18.user.v1.CreateApiKeyReq\x1a\x18.user.v1.CreateApiKeyRes\x12?\n" +
	"\vListApiKeys\x12\x17.user.v1.ListApiKeysReq\x1a\x17.user.v1.ListApiKeysRes\x12B\n" +
	"\fDeleteApiKey\x12\x18.user.v1.DeleteApiKeyReq\x1a\x18.user.v1.DeleteApiKeyRes\x123\n" +
	"\aGetUser\x12\x13.user.v1.GetUserReq\x1a\x13.user.v1.GetUserResB Z\x1eai-platform/api/user/v1;userv1b\x06proto3"

var (
	file_proto_user_v1_user_proto_rawDescOnce sync.Once
	file_proto_user_v1_user_proto_rawDescData []byte
)

func file_proto_user_v1_user_proto_rawDescGZIP() []byte {
	file_proto_user_v1_user_proto_rawDescOnce.Do(func() {
		file_proto_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_v1_user_proto_rawDesc), len(file_proto_user_v1_user_proto_rawDesc)))
	})
	return file_proto_user_v1_user_proto_rawDescData
}

var file_proto_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_user_v1_user_proto_goTypes = []any{
	(*User)(nil),             // 0: user.v1.User
	(*Tenant)(nil),           // 1: user.v1.Tenant
	(*ApiKey)(nil),           // 2: user.v1.ApiKey
	(*Role)(nil),             // 3: user.v1.Role
	(*Permission)(nil),       // 4: user.v1.Permission
	(*RegisterReq)(nil),      // 5: user.v1.RegisterReq
	(*RegisterRes)(nil),      // 6: user.v1.RegisterRes
	(*LoginReq)(nil),         // 7: user.v1.LoginReq
	(*LoginRes)(nil),         // 8: user.v1.LoginRes
	(*ValidateTokenReq)(nil), // 9: user.v1.ValidateTokenReq
	(*ValidateTokenRes)(nil), // 10: user.v1.ValidateTokenRes
	(*CreateApiKeyReq)(nil),  // 11: user.v1.CreateApiKeyReq
	(*CreateApiKeyRes)(nil),  // 12: user.v1.CreateApiKeyRes
	(*ListApiKeysReq)(nil),   // 13: user.v1.ListApiKeysReq
	(*ListApiKeysRes)(nil),   // 14: user.v1.ListApiKeysRes
	(*DeleteApiKeyReq)(nil),  // 15: user.v1.DeleteApiKeyReq
	(*DeleteApiKeyRes)(nil),  // 16: user.v1.DeleteApiKeyRes
	(*GetUserReq)(nil),       // 17: user.v1.GetUserReq
	(*GetUserRes)(nil),       // 18: user.v1.GetUserRes
}
var file_proto_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.RegisterRes.user:type_name -> user.v1.User
	0,  // 1: user.v1.LoginRes.user:type_name -> user.v1.User
	2,  // 2: user.v1.CreateApiKeyRes.api_key:type_name -> user.v1.ApiKey
	2,  // 3: user.v1.ListApiKeysRes.api_keys:type_name -> user.v1.ApiKey
	0,  // 4: user.v1.GetUserRes.user:type_name -> user.v1.User
	5,  // 5: user.v1.UserService.Register:input_type -> user.v1.RegisterReq
	7,  // 6: user.v1.UserService.Login:input_type -> user.v1.LoginReq
	9,  // 7: user.v1.UserService.ValidateToken:input_type -> user.v1.ValidateTokenReq
	11, // 8: user.v1.UserService.CreateApiKey:input_type -> user.v1.CreateApiKeyReq
	13, // 9: user.v1.UserService.ListApiKeys:input_type -> user.v1.ListApiKeysReq
	15, // 10: user.v1.UserService.DeleteApiKey:input_type -> user.v1.DeleteApiKeyReq
	17, // 11: user.v1.UserService.GetUser:input_type -> user.v1.GetUserReq
	6,  // 12: user.v1.UserService.Register:output_type -> user.v1.RegisterRes
	8,  // 13: user.v1.UserService.Login:output_type -> user.v1.LoginRes
	10, // 14: user.v1.UserService.ValidateToken:output_type -> user.v1.ValidateTokenRes
	12, // 15: user.v1.UserService.CreateApiKey:output_type -> user.v1.CreateApiKeyRes
	14, // 16: user.v1.UserService.ListApiKeys:output_type -> user.v1.ListApiKeysRes
	16, // 17: user.v1.UserService.DeleteApiKey:output_type -> user.v1.DeleteApiKeyRes
	18, // 18: user.v1.UserService.GetUser:output_type -> user.v1.GetUserRes
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_user_v1_user_proto_init() }
func file_proto_user_v1_user_proto_init() {
	if File_proto_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_v1_user_proto_rawDesc), len(file_proto_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_v1_user_proto_goTypes,
		DependencyIndexes: file_proto_user_v1_user_proto_depIdxs,
		MessageInfos:      file_proto_user_v1_user_proto_msgTypes,
	}.Build()
	File_proto_user_v1_user_proto = out.File
	file_proto_user_v1_user_proto_goTypes = nil
	file_proto_user_v1_user_proto_depIdxs = nil
}
