// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/asset/v1/asset.proto

package assetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AssetService_CreateOrder_FullMethodName      = "/asset.v1.AssetService/CreateOrder"
	AssetService_GetBalance_FullMethodName       = "/asset.v1.AssetService/GetBalance"
	AssetService_ReportUsage_FullMethodName      = "/asset.v1.AssetService/ReportUsage"
	AssetService_ListTransactions_FullMethodName = "/asset.v1.AssetService/ListTransactions"
	AssetService_ListUsageRecords_FullMethodName = "/asset.v1.AssetService/ListUsageRecords"
	AssetService_CompleteOrder_FullMethodName    = "/asset.v1.AssetService/CompleteOrder"
	AssetService_ListOrders_FullMethodName       = "/asset.v1.AssetService/ListOrders"
	AssetService_RechargeBalance_FullMethodName  = "/asset.v1.AssetService/RechargeBalance"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRes, error)
	GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceRes, error)
	ReportUsage(ctx context.Context, in *ReportUsageReq, opts ...grpc.CallOption) (*ReportUsageRes, error)
	ListTransactions(ctx context.Context, in *ListTransactionsReq, opts ...grpc.CallOption) (*ListTransactionsRes, error)
	ListUsageRecords(ctx context.Context, in *ListUsageRecordsReq, opts ...grpc.CallOption) (*ListUsageRecordsRes, error)
	CompleteOrder(ctx context.Context, in *CompleteOrderReq, opts ...grpc.CallOption) (*CompleteOrderRes, error)
	ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersRes, error)
	RechargeBalance(ctx context.Context, in *RechargeBalanceReq, opts ...grpc.CallOption) (*RechargeBalanceRes, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRes, error) {
	out := new(CreateOrderRes)
	err := c.cc.Invoke(ctx, AssetService_CreateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceRes, error) {
	out := new(GetBalanceRes)
	err := c.cc.Invoke(ctx, AssetService_GetBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ReportUsage(ctx context.Context, in *ReportUsageReq, opts ...grpc.CallOption) (*ReportUsageRes, error) {
	out := new(ReportUsageRes)
	err := c.cc.Invoke(ctx, AssetService_ReportUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsReq, opts ...grpc.CallOption) (*ListTransactionsRes, error) {
	out := new(ListTransactionsRes)
	err := c.cc.Invoke(ctx, AssetService_ListTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ListUsageRecords(ctx context.Context, in *ListUsageRecordsReq, opts ...grpc.CallOption) (*ListUsageRecordsRes, error) {
	out := new(ListUsageRecordsRes)
	err := c.cc.Invoke(ctx, AssetService_ListUsageRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CompleteOrder(ctx context.Context, in *CompleteOrderReq, opts ...grpc.CallOption) (*CompleteOrderRes, error) {
	out := new(CompleteOrderRes)
	err := c.cc.Invoke(ctx, AssetService_CompleteOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersRes, error) {
	out := new(ListOrdersRes)
	err := c.cc.Invoke(ctx, AssetService_ListOrders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) RechargeBalance(ctx context.Context, in *RechargeBalanceReq, opts ...grpc.CallOption) (*RechargeBalanceRes, error) {
	out := new(RechargeBalanceRes)
	err := c.cc.Invoke(ctx, AssetService_RechargeBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility
type AssetServiceServer interface {
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderRes, error)
	GetBalance(context.Context, *GetBalanceReq) (*GetBalanceRes, error)
	ReportUsage(context.Context, *ReportUsageReq) (*ReportUsageRes, error)
	ListTransactions(context.Context, *ListTransactionsReq) (*ListTransactionsRes, error)
	ListUsageRecords(context.Context, *ListUsageRecordsReq) (*ListUsageRecordsRes, error)
	CompleteOrder(context.Context, *CompleteOrderReq) (*CompleteOrderRes, error)
	ListOrders(context.Context, *ListOrdersReq) (*ListOrdersRes, error)
	RechargeBalance(context.Context, *RechargeBalanceReq) (*RechargeBalanceRes, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAssetServiceServer struct {
}

func (UnimplementedAssetServiceServer) CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedAssetServiceServer) GetBalance(context.Context, *GetBalanceReq) (*GetBalanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedAssetServiceServer) ReportUsage(context.Context, *ReportUsageReq) (*ReportUsageRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportUsage not implemented")
}
func (UnimplementedAssetServiceServer) ListTransactions(context.Context, *ListTransactionsReq) (*ListTransactionsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedAssetServiceServer) ListUsageRecords(context.Context, *ListUsageRecordsReq) (*ListUsageRecordsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsageRecords not implemented")
}
func (UnimplementedAssetServiceServer) CompleteOrder(context.Context, *CompleteOrderReq) (*CompleteOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteOrder not implemented")
}
func (UnimplementedAssetServiceServer) ListOrders(context.Context, *ListOrdersReq) (*ListOrdersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedAssetServiceServer) RechargeBalance(context.Context, *RechargeBalanceReq) (*RechargeBalanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RechargeBalance not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetBalance(ctx, req.(*GetBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ReportUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUsageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ReportUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ReportUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ReportUsage(ctx, req.(*ReportUsageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ListTransactions(ctx, req.(*ListTransactionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ListUsageRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsageRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ListUsageRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ListUsageRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ListUsageRecords(ctx, req.(*ListUsageRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CompleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CompleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CompleteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CompleteOrder(ctx, req.(*CompleteOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ListOrders(ctx, req.(*ListOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_RechargeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).RechargeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_RechargeBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).RechargeBalance(ctx, req.(*RechargeBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset.v1.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _AssetService_CreateOrder_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _AssetService_GetBalance_Handler,
		},
		{
			MethodName: "ReportUsage",
			Handler:    _AssetService_ReportUsage_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _AssetService_ListTransactions_Handler,
		},
		{
			MethodName: "ListUsageRecords",
			Handler:    _AssetService_ListUsageRecords_Handler,
		},
		{
			MethodName: "CompleteOrder",
			Handler:    _AssetService_CompleteOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _AssetService_ListOrders_Handler,
		},
		{
			MethodName: "RechargeBalance",
			Handler:    _AssetService_RechargeBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asset/v1/asset.proto",
}
