// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/asset/v1/asset.proto

package assetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Provider       string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUserId int64                  `protobuf:"varint,7,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	Price          float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	ModelName      string                 `protobuf:"bytes,9,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Stock          int32                  `protobuf:"varint,11,opt,name=stock,proto3" json:"stock,omitempty"`
	SoldCount      int32                  `protobuf:"varint,12,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Product) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Product) GetProviderUserId() int64 {
	if x != nil {
		return x.ProviderUserId
	}
	return 0
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo        string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalAmount    float64                `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaymentMethod  string                 `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentTradeNo string                 `protobuf:"bytes,8,opt,name=payment_trade_no,json=paymentTradeNo,proto3" json:"payment_trade_no,omitempty"`
	PaidAt         string                 `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Order) GetPaymentTradeNo() string {
	if x != nil {
		return x.PaymentTradeNo
	}
	return ""
}

func (x *Order) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type Balance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance        float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	TotalRecharged float64                `protobuf:"fixed64,3,opt,name=total_recharged,json=totalRecharged,proto3" json:"total_recharged,omitempty"`
	TotalConsumed  float64                `protobuf:"fixed64,4,opt,name=total_consumed,json=totalConsumed,proto3" json:"total_consumed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{2}
}

func (x *Balance) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Balance) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Balance) GetTotalRecharged() float64 {
	if x != nil {
		return x.TotalRecharged
	}
	return 0
}

func (x *Balance) GetTotalConsumed() float64 {
	if x != nil {
		return x.TotalConsumed
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceBefore float64                `protobuf:"fixed64,5,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"`
	BalanceAfter  float64                `protobuf:"fixed64,6,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	ReferenceType string                 `protobuf:"bytes,7,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId   int64                  `protobuf:"varint,8,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetBalanceBefore() float64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *Transaction) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *Transaction) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *Transaction) GetReferenceId() int64 {
	if x != nil {
		return x.ReferenceId
	}
	return 0
}

func (x *Transaction) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UsageRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKeyId         int64                  `protobuf:"varint,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	ModelName        string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Quota            float64                `protobuf:"fixed64,7,opt,name=quota,proto3" json:"quota,omitempty"`
	RequestId        string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UsageRecord) Reset() {
	*x = UsageRecord{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRecord) ProtoMessage() {}

func (x *UsageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRecord.ProtoReflect.Descriptor instead.
func (*UsageRecord) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{4}
}

func (x *UsageRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsageRecord) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UsageRecord) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *UsageRecord) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *UsageRecord) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *UsageRecord) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *UsageRecord) GetQuota() float64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *UsageRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateOrderReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderReq) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CreateOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PayUrl        string                 `protobuf:"bytes,2,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRes) Reset() {
	*x = CreateOrderRes{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRes) ProtoMessage() {}

func (x *CreateOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRes.ProtoReflect.Descriptor instead.
func (*CreateOrderRes) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderRes) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderRes) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

type GetBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceReq) Reset() {
	*x = GetBalanceReq{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceReq) ProtoMessage() {}

func (x *GetBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceReq.ProtoReflect.Descriptor instead.
func (*GetBalanceReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalanceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBalanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRes) Reset() {
	*x = GetBalanceRes{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRes) ProtoMessage() {}

func (x *GetBalanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRes.ProtoReflect.Descriptor instead.
func (*GetBalanceRes) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalanceRes) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type ReportUsageReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKeyId         int64                  `protobuf:"varint,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	ModelName        string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Quota            float64                `protobuf:"fixed64,6,opt,name=quota,proto3" json:"quota,omitempty"`
	RequestId        string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChannelId        int64                  `protobuf:"varint,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName      string                 `protobuf:"bytes,9,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportUsageReq) Reset() {
	*x = ReportUsageReq{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageReq) ProtoMessage() {}

func (x *ReportUsageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageReq.ProtoReflect.Descriptor instead.
func (*ReportUsageReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{9}
}

func (x *ReportUsageReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportUsageReq) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *ReportUsageReq) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ReportUsageReq) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ReportUsageReq) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ReportUsageReq) GetQuota() float64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *ReportUsageReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReportUsageReq) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ReportUsageReq) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type ReportUsageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceAfter  float64                `protobuf:"fixed64,1,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageRes) Reset() {
	*x = ReportUsageRes{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageRes) ProtoMessage() {}

func (x *ReportUsageRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageRes.ProtoReflect.Descriptor instead.
func (*ReportUsageRes) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{10}
}

func (x *ReportUsageRes) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

type ListTransactionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsReq) Reset() {
	*x = ListTransactionsReq{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsReq) ProtoMessage() {}

func (x *ListTransactionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsReq.ProtoReflect.Descriptor instead.
func (*ListTransactionsReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{11}
}

func (x *ListTransactionsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTransactionsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTransactionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRes) Reset() {
	*x = ListTransactionsRes{}
	mi := &file_proto_asset_v1_asset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRes) ProtoMessage() {}

func (x *ListTransactionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_v1_asset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRes.ProtoReflect.Descriptor instead.
func (*ListTransactionsRes) Descriptor() ([]byte, []int) {
	return file_proto_asset_v1_asset_proto_rawDescGZIP(), []int{12}
}

func (x *ListTransactionsRes) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_asset_v1_asset_proto protoreflect.FileDescriptor

const file_proto_asset_v1_asset_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/asset/v1/asset.proto\x12\basset.v1\"\xc8\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\a \x01(\x03R\x0eproviderUserId\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"model_name\x18\t \x01(\tR\tmodelName\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x14\n" +
	"\x05stock\x18\v \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\f \x01(\x05R\tsoldCount\"\x84\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x01R\vtotalAmount\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\x12(\n" +
	"\x10payment_trade_no\x18\b \x01(\tR\x0epaymentTradeNo\x12\x17\n" +
	"\apaid_at\x18\t \x01(\tR\x06paidAt\"\x8c\x01\n" +
	"\aBalance\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12'\n" +
	"\x0ftotal_recharged\x18\x03 \x01(\x01R\x0etotalRecharged\x12%\n" +
	"\x0etotal_consumed\x18\x04 \x01(\x01R\rtotalConsumed\"\x90\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12%\n" +
	"\x0ebalance_before\x18\x05 \x01(\x01R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\x06 \x01(\x01R\fbalanceAfter\x12%\n" +
	"\x0ereference_type\x18\a \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\b \x01(\x03R\vreferenceId\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\"\xfa\x01\n" +
	"\vUsageRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x03 \x01(\x03R\bapiKeyId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x05R\x10completionTokens\x12\x14\n" +
	"\x05quota\x18\a \x01(\x01R\x05quota\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\"|\n" +
	"\x0eCreateOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\"P\n" +
	"\x0eCreateOrderRes\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.asset.v1.OrderR\x05order\x12\x17\n" +
	"\apay_url\x18\x02 \x01(\tR\x06payUrl\"(\n" +
	"\rGetBalanceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"<\n" +
	"\rGetBalanceRes\x12+\n" +
	"\abalance\x18\x01 \x01(\v2\x11.asset.v1.BalanceR\abalance\"\xaf\x02\n" +
	"\x0eReportUsageReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\x03R\bapiKeyId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x05R\x10completionTokens\x12\x14\n" +
	"\x05quota\x18\x06 \x01(\x01R\x05quota\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\b \x01(\x03R\tchannelId\x12!\n" +
	"\fchannel_name\x18\t \x01(\tR\vchannelName\"5\n" +
	"\x0eReportUsageRes\x12#\n" +
	"\rbalance_after\x18\x01 \x01(\x01R\fbalanceAfter\"_\n" +
	"\x13ListTransactionsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"f\n" +
	"\x13ListTransactionsRes\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.asset.v1.TransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xa6\x02\n" +
	"\fAssetService\x12A\n" +
	"\vCreateOrder\x12\x18.asset.v1.CreateOrderReq\x1a\x18.asset.v1.CreateOrderRes\x12>\n" +
	"\n" +
	"GetBalance\x12\x17.asset.v1.GetBalanceReq\x1a\x17.asset.v1.GetBalanceRes\x12A\n" +
	"\vReportUsage\x12\x18.asset.v1.ReportUsageReq\x1a\x18.asset.v1.ReportUsageRes\x12P\n" +
	"\x10ListTransactions\x12\x1d.asset.v1.ListTransactionsReq\x1a\x1d.asset.v1.ListTransactionsResB\"Z ai-platform/api/asset/v1;assetv1b\x06proto3"

var (
	file_proto_asset_v1_asset_proto_rawDescOnce sync.Once
	file_proto_asset_v1_asset_proto_rawDescData []byte
)

func file_proto_asset_v1_asset_proto_rawDescGZIP() []byte {
	file_proto_asset_v1_asset_proto_rawDescOnce.Do(func() {
		file_proto_asset_v1_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_v1_asset_proto_rawDesc), len(file_proto_asset_v1_asset_proto_rawDesc)))
	})
	return file_proto_asset_v1_asset_proto_rawDescData
}

var file_proto_asset_v1_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_asset_v1_asset_proto_goTypes = []any{
	(*Product)(nil),             // 0: asset.v1.Product
	(*Order)(nil),               // 1: asset.v1.Order
	(*Balance)(nil),             // 2: asset.v1.Balance
	(*Transaction)(nil),         // 3: asset.v1.Transaction
	(*UsageRecord)(nil),         // 4: asset.v1.UsageRecord
	(*CreateOrderReq)(nil),      // 5: asset.v1.CreateOrderReq
	(*CreateOrderRes)(nil),      // 6: asset.v1.CreateOrderRes
	(*GetBalanceReq)(nil),       // 7: asset.v1.GetBalanceReq
	(*GetBalanceRes)(nil),       // 8: asset.v1.GetBalanceRes
	(*ReportUsageReq)(nil),      // 9: asset.v1.ReportUsageReq
	(*ReportUsageRes)(nil),      // 10: asset.v1.ReportUsageRes
	(*ListTransactionsReq)(nil), // 11: asset.v1.ListTransactionsReq
	(*ListTransactionsRes)(nil), // 12: asset.v1.ListTransactionsRes
}
var file_proto_asset_v1_asset_proto_depIdxs = []int32{
	1,  // 0: asset.v1.CreateOrderRes.order:type_name -> asset.v1.Order
	2,  // 1: asset.v1.GetBalanceRes.balance:type_name -> asset.v1.Balance
	3,  // 2: asset.v1.ListTransactionsRes.transactions:type_name -> asset.v1.Transaction
	5,  // 3: asset.v1.AssetService.CreateOrder:input_type -> asset.v1.CreateOrderReq
	7,  // 4: asset.v1.AssetService.GetBalance:input_type -> asset.v1.GetBalanceReq
	9,  // 5: asset.v1.AssetService.ReportUsage:input_type -> asset.v1.ReportUsageReq
	11, // 6: asset.v1.AssetService.ListTransactions:input_type -> asset.v1.ListTransactionsReq
	6,  // 7: asset.v1.AssetService.CreateOrder:output_type -> asset.v1.CreateOrderRes
	8,  // 8: asset.v1.AssetService.GetBalance:output_type -> asset.v1.GetBalanceRes
	10, // 9: asset.v1.AssetService.ReportUsage:output_type -> asset.v1.ReportUsageRes
	12, // 10: asset.v1.AssetService.ListTransactions:output_type -> asset.v1.ListTransactionsRes
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_asset_v1_asset_proto_init() }
func file_proto_asset_v1_asset_proto_init() {
	if File_proto_asset_v1_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_v1_asset_proto_rawDesc), len(file_proto_asset_v1_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asset_v1_asset_proto_goTypes,
		DependencyIndexes: file_proto_asset_v1_asset_proto_depIdxs,
		MessageInfos:      file_proto_asset_v1_asset_proto_msgTypes,
	}.Build()
	File_proto_asset_v1_asset_proto = out.File
	file_proto_asset_v1_asset_proto_goTypes = nil
	file_proto_asset_v1_asset_proto_depIdxs = nil
}
