// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/market/v1/market.proto

package marketv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketService_CreateListing_FullMethodName = "/market.v1.MarketService/CreateListing"
	MarketService_ListListings_FullMethodName  = "/market.v1.MarketService/ListListings"
	MarketService_BuyProduct_FullMethodName    = "/market.v1.MarketService/BuyProduct"
	MarketService_ListTrades_FullMethodName    = "/market.v1.MarketService/ListTrades"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	CreateListing(ctx context.Context, in *CreateListingReq, opts ...grpc.CallOption) (*CreateListingRes, error)
	ListListings(ctx context.Context, in *ListListingsReq, opts ...grpc.CallOption) (*ListListingsRes, error)
	BuyProduct(ctx context.Context, in *BuyProductReq, opts ...grpc.CallOption) (*BuyProductRes, error)
	ListTrades(ctx context.Context, in *ListTradesReq, opts ...grpc.CallOption) (*ListTradesRes, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) CreateListing(ctx context.Context, in *CreateListingReq, opts ...grpc.CallOption) (*CreateListingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateListingRes)
	err := c.cc.Invoke(ctx, MarketService_CreateListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) ListListings(ctx context.Context, in *ListListingsReq, opts ...grpc.CallOption) (*ListListingsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListListingsRes)
	err := c.cc.Invoke(ctx, MarketService_ListListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) BuyProduct(ctx context.Context, in *BuyProductReq, opts ...grpc.CallOption) (*BuyProductRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyProductRes)
	err := c.cc.Invoke(ctx, MarketService_BuyProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) ListTrades(ctx context.Context, in *ListTradesReq, opts ...grpc.CallOption) (*ListTradesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTradesRes)
	err := c.cc.Invoke(ctx, MarketService_ListTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility.
type MarketServiceServer interface {
	CreateListing(context.Context, *CreateListingReq) (*CreateListingRes, error)
	ListListings(context.Context, *ListListingsReq) (*ListListingsRes, error)
	BuyProduct(context.Context, *BuyProductReq) (*BuyProductRes, error)
	ListTrades(context.Context, *ListTradesReq) (*ListTradesRes, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) CreateListing(context.Context, *CreateListingReq) (*CreateListingRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateListing not implemented")
}
func (UnimplementedMarketServiceServer) ListListings(context.Context, *ListListingsReq) (*ListListingsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListListings not implemented")
}
func (UnimplementedMarketServiceServer) BuyProduct(context.Context, *BuyProductReq) (*BuyProductRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BuyProduct not implemented")
}
func (UnimplementedMarketServiceServer) ListTrades(context.Context, *ListTradesReq) (*ListTradesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrades not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}
func (UnimplementedMarketServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_CreateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).CreateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_CreateListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).CreateListing(ctx, req.(*CreateListingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ListListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListListingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ListListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ListListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ListListings(ctx, req.(*ListListingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_BuyProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).BuyProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_BuyProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).BuyProduct(ctx, req.(*BuyProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ListTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTradesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ListTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ListTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ListTrades(ctx, req.(*ListTradesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.v1.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateListing",
			Handler:    _MarketService_CreateListing_Handler,
		},
		{
			MethodName: "ListListings",
			Handler:    _MarketService_ListListings_Handler,
		},
		{
			MethodName: "BuyProduct",
			Handler:    _MarketService_BuyProduct_Handler,
		},
		{
			MethodName: "ListTrades",
			Handler:    _MarketService_ListTrades_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/market/v1/market.proto",
}
