// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/market/v1/market.proto

package marketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SellerId      int64                  `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	ProductType   string                 `protobuf:"bytes,3,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Sold          int32                  `protobuf:"varint,8,opt,name=sold,proto3" json:"sold,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_proto_market_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Listing) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *Listing) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *Listing) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Listing) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Listing) GetSold() int32 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *Listing) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ListingId     int64                  `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	BuyerId       int64                  `protobuf:"varint,3,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId      int64                  `protobuf:"varint,4,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PlatformFee   float64                `protobuf:"fixed64,6,opt,name=platform_fee,json=platformFee,proto3" json:"platform_fee,omitempty"`
	SellerIncome  float64                `protobuf:"fixed64,7,opt,name=seller_income,json=sellerIncome,proto3" json:"seller_income,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_proto_market_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *Trade) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trade) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *Trade) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *Trade) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *Trade) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Trade) GetPlatformFee() float64 {
	if x != nil {
		return x.PlatformFee
	}
	return 0
}

func (x *Trade) GetSellerIncome() float64 {
	if x != nil {
		return x.SellerIncome
	}
	return 0
}

func (x *Trade) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateListingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      int64                  `protobuf:"varint,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	ProductType   string                 `protobuf:"bytes,2,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingReq) Reset() {
	*x = CreateListingReq{}
	mi := &file_proto_market_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingReq) ProtoMessage() {}

func (x *CreateListingReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingReq.ProtoReflect.Descriptor instead.
func (*CreateListingReq) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *CreateListingReq) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *CreateListingReq) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *CreateListingReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateListingReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateListingReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateListingReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateListingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *Listing               `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRes) Reset() {
	*x = CreateListingRes{}
	mi := &file_proto_market_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRes) ProtoMessage() {}

func (x *CreateListingRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRes.ProtoReflect.Descriptor instead.
func (*CreateListingRes) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *CreateListingRes) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

type ListListingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProductType   string                 `protobuf:"bytes,2,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListingsReq) Reset() {
	*x = ListListingsReq{}
	mi := &file_proto_market_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListingsReq) ProtoMessage() {}

func (x *ListListingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListingsReq.ProtoReflect.Descriptor instead.
func (*ListListingsReq) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *ListListingsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListListingsReq) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *ListListingsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListListingsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListListingsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListingsRes) Reset() {
	*x = ListListingsRes{}
	mi := &file_proto_market_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListingsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListingsRes) ProtoMessage() {}

func (x *ListListingsRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListingsRes.ProtoReflect.Descriptor instead.
func (*ListListingsRes) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *ListListingsRes) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *ListListingsRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BuyProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	BuyerId       int64                  `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyProductReq) Reset() {
	*x = BuyProductReq{}
	mi := &file_proto_market_v1_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyProductReq) ProtoMessage() {}

func (x *BuyProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyProductReq.ProtoReflect.Descriptor instead.
func (*BuyProductReq) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{6}
}

func (x *BuyProductReq) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *BuyProductReq) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *BuyProductReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BuyProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trade         *Trade                 `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyProductRes) Reset() {
	*x = BuyProductRes{}
	mi := &file_proto_market_v1_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyProductRes) ProtoMessage() {}

func (x *BuyProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyProductRes.ProtoReflect.Descriptor instead.
func (*BuyProductRes) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{7}
}

func (x *BuyProductRes) GetTrade() *Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

type ListTradesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesReq) Reset() {
	*x = ListTradesReq{}
	mi := &file_proto_market_v1_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesReq) ProtoMessage() {}

func (x *ListTradesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesReq.ProtoReflect.Descriptor instead.
func (*ListTradesReq) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{8}
}

func (x *ListTradesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTradesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTradesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTradesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesRes) Reset() {
	*x = ListTradesRes{}
	mi := &file_proto_market_v1_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesRes) ProtoMessage() {}

func (x *ListTradesRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_v1_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesRes.ProtoReflect.Descriptor instead.
func (*ListTradesRes) Descriptor() ([]byte, []int) {
	return file_proto_market_v1_market_proto_rawDescGZIP(), []int{9}
}

func (x *ListTradesRes) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *ListTradesRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_market_v1_market_proto protoreflect.FileDescriptor

const file_proto_market_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/market/v1/market.proto\x12\tmarket.v1\"\xef\x01\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x03R\bsellerId\x12!\n" +
	"\fproduct_type\x18\x03 \x01(\tR\vproductType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x12\n" +
	"\x04sold\x18\b \x01(\x05R\x04sold\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\xe6\x01\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\x03R\tlistingId\x12\x19\n" +
	"\bbuyer_id\x18\x03 \x01(\x03R\abuyerId\x12\x1b\n" +
	"\tseller_id\x18\x04 \x01(\x03R\bsellerId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12!\n" +
	"\fplatform_fee\x18\x06 \x01(\x01R\vplatformFee\x12#\n" +
	"\rseller_income\x18\a \x01(\x01R\fsellerIncome\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\xbc\x01\n" +
	"\x10CreateListingReq\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\x03R\bsellerId\x12!\n" +
	"\fproduct_type\x18\x02 \x01(\tR\vproductType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\"@\n" +
	"\x10CreateListingRes\x12,\n" +
	"\alisting\x18\x01 \x01(\v2\x12.market.v1.ListingR\alisting\"}\n" +
	"\x0fListListingsReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fproduct_type\x18\x02 \x01(\tR\vproductType\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"W\n" +
	"\x0fListListingsRes\x12.\n" +
	"\blistings\x18\x01 \x03(\v2\x12.market.v1.ListingR\blistings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"e\n" +
	"\rBuyProductReq\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x03R\abuyerId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"7\n" +
	"\rBuyProductRes\x12&\n" +
	"\x05trade\x18\x01 \x01(\v2\x10.market.v1.TradeR\x05trade\"Y\n" +
	"\rListTradesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"O\n" +
	"\rListTradesRes\x12(\n" +
	"\x06trades\x18\x01 \x03(\v2\x10.market.v1.TradeR\x06trades\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xa6\x02\n" +
	"\rMarketService\x12I\n" +
	"\rCreateListing\x12\x1b.market.v1.CreateListingReq\x1a\x1b.market.v1.CreateListingRes\x12F\n" +
	"\fListListings\x12\x1a.market.v1.ListListingsReq\x1a\x1a.market.v1.ListListingsRes\x12@\n" +
	"\n" +
	"BuyProduct\x12\x18.market.v1.BuyProductReq\x1a\x18.market.v1.BuyProductRes\x12@\n" +
	"\n" +
	"ListTrades\x12\x18.market.v1.ListTradesReq\x1a\x18.market.v1.ListTradesResB$Z\"ai-platform/api/market/v1;marketv1b\x06proto3"

var (
	file_proto_market_v1_market_proto_rawDescOnce sync.Once
	file_proto_market_v1_market_proto_rawDescData []byte
)

func file_proto_market_v1_market_proto_rawDescGZIP() []byte {
	file_proto_market_v1_market_proto_rawDescOnce.Do(func() {
		file_proto_market_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_market_v1_market_proto_rawDesc), len(file_proto_market_v1_market_proto_rawDesc)))
	})
	return file_proto_market_v1_market_proto_rawDescData
}

var file_proto_market_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_market_v1_market_proto_goTypes = []any{
	(*Listing)(nil),          // 0: market.v1.Listing
	(*Trade)(nil),            // 1: market.v1.Trade
	(*CreateListingReq)(nil), // 2: market.v1.CreateListingReq
	(*CreateListingRes)(nil), // 3: market.v1.CreateListingRes
	(*ListListingsReq)(nil),  // 4: market.v1.ListListingsReq
	(*ListListingsRes)(nil),  // 5: market.v1.ListListingsRes
	(*BuyProductReq)(nil),    // 6: market.v1.BuyProductReq
	(*BuyProductRes)(nil),    // 7: market.v1.BuyProductRes
	(*ListTradesReq)(nil),    // 8: market.v1.ListTradesReq
	(*ListTradesRes)(nil),    // 9: market.v1.ListTradesRes
}
var file_proto_market_v1_market_proto_depIdxs = []int32{
	0, // 0: market.v1.CreateListingRes.listing:type_name -> market.v1.Listing
	0, // 1: market.v1.ListListingsRes.listings:type_name -> market.v1.Listing
	1, // 2: market.v1.BuyProductRes.trade:type_name -> market.v1.Trade
	1, // 3: market.v1.ListTradesRes.trades:type_name -> market.v1.Trade
	2, // 4: market.v1.MarketService.CreateListing:input_type -> market.v1.CreateListingReq
	4, // 5: market.v1.MarketService.ListListings:input_type -> market.v1.ListListingsReq
	6, // 6: market.v1.MarketService.BuyProduct:input_type -> market.v1.BuyProductReq
	8, // 7: market.v1.MarketService.ListTrades:input_type -> market.v1.ListTradesReq
	3, // 8: market.v1.MarketService.CreateListing:output_type -> market.v1.CreateListingRes
	5, // 9: market.v1.MarketService.ListListings:output_type -> market.v1.ListListingsRes
	7, // 10: market.v1.MarketService.BuyProduct:output_type -> market.v1.BuyProductRes
	9, // 11: market.v1.MarketService.ListTrades:output_type -> market.v1.ListTradesRes
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_market_v1_market_proto_init() }
func file_proto_market_v1_market_proto_init() {
	if File_proto_market_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_market_v1_market_proto_rawDesc), len(file_proto_market_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_market_v1_market_proto_goTypes,
		DependencyIndexes: file_proto_market_v1_market_proto_depIdxs,
		MessageInfos:      file_proto_market_v1_market_proto_msgTypes,
	}.Build()
	File_proto_market_v1_market_proto = out.File
	file_proto_market_v1_market_proto_goTypes = nil
	file_proto_market_v1_market_proto_depIdxs = nil
}
