// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset-svc/internal/dao/internal"
)

// balancesDao is the data access object for the table balances.
// You can define custom methods on it to extend its functionality as needed.
type balancesDao struct {
	*internal.BalancesDao
}

var (
	// Balances is a globally accessible object for table balances operations.
	Balances = balancesDao{internal.NewBalancesDao()}
)

// Add your custom methods and functionality below.
