// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset-svc/internal/dao/internal"
)

// usageRecordsDao is the data access object for the table usage_records.
// You can define custom methods on it to extend its functionality as needed.
type usageRecordsDao struct {
	*internal.UsageRecordsDao
}

var (
	// UsageRecords is a globally accessible object for table usage_records operations.
	UsageRecords = usageRecordsDao{internal.NewUsageRecordsDao()}
)

// Add your custom methods and functionality below.
