// Type declaration for the TanStack Router generated route tree.
// The actual routeTree.gen.ts is generated by the Vite plugin at build time.
declare module './routeTree.gen' {
  import type { Route } from '@tanstack/react-router'
  export const routeTree: Route
}
