// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyReq) Reset() {
	*x = ValidateKeyReq{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyReq) ProtoMessage() {}

func (x *ValidateKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyReq.ProtoReflect.Descriptor instead.
func (*ValidateKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateKeyReq) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ValidateKeyReq) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ValidateKeyReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type ValidateKeyRes struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Valid              bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEnabled        bool                   `protobuf:"varint,3,opt,name=user_enabled,json=userEnabled,proto3" json:"user_enabled,omitempty"`
	Group              string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	ModelLimitsEnabled bool                   `protobuf:"varint,5,opt,name=model_limits_enabled,json=modelLimitsEnabled,proto3" json:"model_limits_enabled,omitempty"`
	ModelLimits        []string               `protobuf:"bytes,6,rep,name=model_limits,json=modelLimits,proto3" json:"model_limits,omitempty"`
	ApiKeyId           int64                  `protobuf:"varint,7,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidateKeyRes) Reset() {
	*x = ValidateKeyRes{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyRes) ProtoMessage() {}

func (x *ValidateKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyRes.ProtoReflect.Descriptor instead.
func (*ValidateKeyRes) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateKeyRes) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateKeyRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateKeyRes) GetUserEnabled() bool {
	if x != nil {
		return x.UserEnabled
	}
	return false
}

func (x *ValidateKeyRes) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ValidateKeyRes) GetModelLimitsEnabled() bool {
	if x != nil {
		return x.ModelLimitsEnabled
	}
	return false
}

func (x *ValidateKeyRes) GetModelLimits() []string {
	if x != nil {
		return x.ModelLimits
	}
	return nil
}

func (x *ValidateKeyRes) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

type ReportUsageReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKeyId         int64                  `protobuf:"varint,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	ModelName        string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Quota            float64                `protobuf:"fixed64,6,opt,name=quota,proto3" json:"quota,omitempty"`
	RequestId        string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportUsageReq) Reset() {
	*x = ReportUsageReq{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageReq) ProtoMessage() {}

func (x *ReportUsageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageReq.ProtoReflect.Descriptor instead.
func (*ReportUsageReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ReportUsageReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportUsageReq) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *ReportUsageReq) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ReportUsageReq) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ReportUsageReq) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ReportUsageReq) GetQuota() float64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *ReportUsageReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReportUsageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BalanceAfter  float64                `protobuf:"fixed64,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageRes) Reset() {
	*x = ReportUsageRes{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageRes) ProtoMessage() {}

func (x *ReportUsageRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageRes.ProtoReflect.Descriptor instead.
func (*ReportUsageRes) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ReportUsageRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportUsageRes) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

var File_proto_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"e\n" +
	"\x0eValidateKeyReq\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\"\xeb\x01\n" +
	"\x0eValidateKeyRes\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fuser_enabled\x18\x03 \x01(\bR\vuserEnabled\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x120\n" +
	"\x14model_limits_enabled\x18\x05 \x01(\bR\x12modelLimitsEnabled\x12!\n" +
	"\fmodel_limits\x18\x06 \x03(\tR\vmodelLimits\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\a \x01(\x03R\bapiKeyId\"\xed\x01\n" +
	"\x0eReportUsageReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\x03R\bapiKeyId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x05R\x10completionTokens\x12\x14\n" +
	"\x05quota\x18\x06 \x01(\x01R\x05quota\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"O\n" +
	"\x0eReportUsageRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\x01R\fbalanceAfter2\x9e\x01\n" +
	"\x0eGatewayService\x12E\n" +
	"\vValidateKey\x12\x1a.gateway.v1.ValidateKeyReq\x1a\x1a.gateway.v1.ValidateKeyRes\x12E\n" +
	"\vReportUsage\x12\x1a.gateway.v1.ReportUsageReq\x1a\x1a.gateway.v1.ReportUsageResB&Z$ai-platform/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_proto_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_v1_gateway_proto_rawDescData []byte
)

func file_proto_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_v1_gateway_proto_rawDescData
}

var file_proto_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gateway_v1_gateway_proto_goTypes = []any{
	(*ValidateKeyReq)(nil), // 0: gateway.v1.ValidateKeyReq
	(*ValidateKeyRes)(nil), // 1: gateway.v1.ValidateKeyRes
	(*ReportUsageReq)(nil), // 2: gateway.v1.ReportUsageReq
	(*ReportUsageRes)(nil), // 3: gateway.v1.ReportUsageRes
}
var file_proto_gateway_v1_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.v1.GatewayService.ValidateKey:input_type -> gateway.v1.ValidateKeyReq
	2, // 1: gateway.v1.GatewayService.ReportUsage:input_type -> gateway.v1.ReportUsageReq
	1, // 2: gateway.v1.GatewayService.ValidateKey:output_type -> gateway.v1.ValidateKeyRes
	3, // 3: gateway.v1.GatewayService.ReportUsage:output_type -> gateway.v1.ReportUsageRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_v1_gateway_proto_init() }
func file_proto_gateway_v1_gateway_proto_init() {
	if File_proto_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_v1_gateway_proto = out.File
	file_proto_gateway_v1_gateway_proto_goTypes = nil
	file_proto_gateway_v1_gateway_proto_depIdxs = nil
}
