// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ai-gateway/internal/dao/internal"
)

// abilitiesDao is the data access object for the table abilities.
// You can define custom methods on it to extend its functionality as needed.
type abilitiesDao struct {
	*internal.AbilitiesDao
}

var (
	// Abilities is a globally accessible object for table abilities operations.
	Abilities = abilitiesDao{internal.NewAbilitiesDao()}
)

// Add your custom methods and functionality below.
