// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ai-gateway/internal/dao/internal"
)

// channelsDao is the data access object for the table channels.
// You can define custom methods on it to extend its functionality as needed.
type channelsDao struct {
	*internal.ChannelsDao
}

var (
	// Channels is a globally accessible object for table channels operations.
	Channels = channelsDao{internal.NewChannelsDao()}
)

// Add your custom methods and functionality below.
